# Generated by Django 5.2.1 on 2025-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
