# Generated by Django 5.2.1 on 2025-05-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_remove_package_created_at_package_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
