# Generated by Django 5.2.1 on 2025-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_package_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_budget_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_top_package',
            field=models.BooleanField(default=False),
        ),
    ]
