# Generated by Django 5.2.1 on 2025-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_package_is_budget_friendly_package_is_top_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
