# Generated by Django 5.2.1 on 2025-05-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0005_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
