# Generated by Django 5.2.1 on 2025-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
